### ISSUE TITLE
Feature Request - High Scores for Total Mastery Score

### ISSUE THREAD

**Issue by MattCopenhaver** [Derpthemeus/ChampionMasteryLookup#10]
Total Mastery Score = Sum of Mastery Level for all champions.

If this is something you agree would be beneficial, I could potentially submit a PR.

**Comment by Derpthemeus** [comment]
I've thought about this before, but haven't done it because there is a cap on the highest possible total level (7 * total number of champions). Eventually multiple players will reach the maximum level on all champions (until a new champion is released), and I can't think of a good way to break ties when this happens. The best way to do it would be based on when they reached the max level, but I can't determine this information (I can only tell when they were looked up on the site, not when they leveled up on the last champion).

I also have a secondary concern that the list might not be very accurate. The site relies on users to look up players so they can be added to the highscores, which works pretty well for people who are dedicated to a single champion - a fair amount of these players are streamers who have become well known for their dedication, and it can be easy to tell when somebody is very experienced on a champion (if you get crushed in game by somebody named "I only play Heimerdinger" who goes 20/0/0 on Heimerdinger, they've probably played a bunch of Heimerdinger). These players are likely to be looked up on the site (either by fans or salty/astonished enemies/teammates) and automatically added to the highscores.
This doesn't work so well for finding players who are a jack of all trades (master of none). I don't think many of these players are streamers (so they won't be looked up by fans) and it's harder to tell if you just played with one of them (so they're less likely to be looked up by recent teammates/enemies). This makes it decently likely that the only way a certain player will be looked up (and added to the highscores) is if they look themselves up, and this won't happen if they don't use the site.

**Comment by MattCopenhaver** [comment]
That's cool if you don't think it would be useful or maintainable - totally respect your opinion on that.

A few counterpoints though:
1. If someone does have all rank 7 already, it would be awesome to be able to see who that is.  
2. Whenever it gets to the point that there are over 20 people with all rank 7, could we just list them all alphabetically?
3. The people that care about getting rank 7 on all champs are probably already using this site lo look themselves up during champ select.
4. I don't see it as a problem that some people are missing if they don't get looked up.  All you can do is do the best with the information you have.  No need to be 100% accurate (the high scores per champion probably aren't 100% accurate, but it's still an awesome feature).  

That's all I'll say, other than: thanks for creating this site.  It's been very helpful during champ select to pick a champion I've not played much and would like to get better at.

**Comment by Derpthemeus** [comment]
All good counterpoints, the only one I don't agree with is # 2 (I don't think a player should be excluded from the list just because of their name). I'm going to give this idea some more consideration and probably add it in soon-ish (I'm currently work on a large rework that I want to finish first, and any updates made now to the live site aren't going to be compatible with the rework).

I'm not sure exactly how it will be implemented, but I'm currently thinking I might make it a flexible list - it would include all players who are max rank (probably sorted by total mastery points), then the top 20 players who have NOT reached the max level.

Thanks for the suggestion and providing a strong argument!

**Comment by MattCopenhaver** [comment]
Sorry if it wasn't clear - for #2, I was thinking a full list, not limited to 20.  Maybe a Top 20 until we get to the point that there are ~20 players who have maxed out, then change it to a full list of maxed out players.

**Comment by Derpthemeus** [comment]
Quick status update: I haven't been able to work on this too much since I've been busy with some other stuff (both project related and non-project related). Progress is going slower than I had originally expected, but I haven't forgotten about this issue.

**Comment by Derpthemeus** [comment]
I could probably spend forever trying to figure out the perfect way to implement this feature, but then I would never add it. The current plan is to use this implementation (a normal highscores table) until it fills up with a lot of players who have reached the maximum level. Once that happens, I'll switch to a different format that only displays players who have reached maximum level (with no limit on how many are displayed), and secondary sorts them by their total mastery points (instead of when they were looked up on the site).

Thanks again for the suggestion!
